server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Documents/study/springcloud/native-file-repo
        git:
#          uri: file://Users/ijinho/Documents/study/springcloud/git-local-repo
          uri: https://github.com/paki1019/spring-cloud-config
#          username: [your username]
#          password: [your password]