server:
  port: 8761

spring:
  application:
    name: discoveryservice

eureka:
  server:
    enable-self-preservation: false # 개발에서만 사용, 운영시 삭제
    eviction-interval-timer-in-ms: 3000 # 하트비트 수신점검 인터벌
  client:
    register-with-eureka: false
    fetch-registry: false